---
- name: Webtest
  hosts: localhost
  become: true

  tasks:
    - name: Check if website is running.
      uri:
        url: "http://127.0.0.1/"
      retries: 60
      register: file_res
      changed_when: false
      until: file_res is success

